### ISSUE TITLE
Is it convenient to provide any data?

### ISSUE THREAD

**Issue by idiomaticrefactoring** [johanvanl/SemDiff#1]
Hello, is it convenient to provide any data?(33 relevant recommendations and the corresponding location in client programs such as JBoss)

**Comment by johanvanl** [comment]
Hi. I am not sure what is being asked here. Something I can help with?

**Comment by idiomaticrefactoring** [comment]
Thanks for your reply. The tables shows Semdiff can recommend 33 APIs to help developers upgrade their programs. Is there any data that we can refer to? ![image](https://user-images.githubusercontent.com/29055749/122355565-95c0b800-cf84-11eb-9c60-562d63bf5d04.png)

**Comment by johanvanl** [comment]
The table above, where was this taken from?

**Comment by idiomaticrefactoring** [comment]
Recommending Adaptive Changes for Framework Evolution.  Barth ´ el ´emy Dagenais and Martin P. Robillard. ICSE2008

**Comment by idiomaticrefactoring** [comment]
I am sorry, maybe I am wrong, the code is not the code that I want to find. 
![image](https://user-images.githubusercontent.com/29055749/122359054-cd7d2f00-cf87-11eb-8515-9b138b1226e4.png)

**Comment by johanvanl** [comment]
Not sure what SemDiff is being referenced here. But it’s definitely not this one.
